//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMVCDemo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tProducts
    {
        public int fId { get; set; }
        [DisplayName("產品名稱")]
        [Required(ErrorMessage = "產品名稱為必填欄位")]
        public string fName { get; set; }
        [DisplayName("成本")]
        public Nullable<decimal> fCost { get; set; }
        [DisplayName("庫存量")]
        public string fQty { get; set; }
        [DisplayName("產品單價")]
        public Nullable<decimal> fPrice { get; set; }
        public string fImagePath { get; set; }
        public HttpPostedFileBase photo { get; set; }
    }
}
